### PR TITLE
Issue7 setup db

### LINKED ISSUE #7: #7setup_db
Refer to:
_PMC Workload for 2023 V1.0, Version to do initial allocation_
From Mark Reynolds

### PR DESCRIPTION
**Pull request by yylocky**
## Change Summary 📝
Setup database model, add a seed script to put some test data.

---

## Change Form 📋
Please mark as NA if not applicable. If a certain criterion is not met, kindly provide a reason.

- [x] The pull request title has an issue number.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [NA] Relevant tests (if applicable) have been added or updated. 

---

## Any background context you want to provide? 🖼️

Any additional context or screenshots that could help the reviewers?
image

## Reviewers 🕵️

(Optional) Suggest reviewers that might be interested in this PR.

### CODE REVIEW

**Comment by kylelhk** [comment]
1. Other than Primary Key, there is only 1 field in the Roles, Login and Departments tables.  Can we add role name and password into the Users table and department name into the Work table so that the Roles, Login and Departments tables can be removed?  That way the corresponding Foreign Keys can also be removed.

2. As discussed before, we may not be working on the verification of hours.  In this case, what is the purpose of having leave_hours, contract_hour and available_hours?  Do we still need to keep track of these hours and build the function for updating leave hours (by extracting data from relevant spreadsheet) in the assign page?

3. Suggested Relationships:
image

**Comment by yylocky** [comment]
> 1. Other than Primary Key, there is only 1 field in the Roles, Login and Departments tables.  Can we add role name and password into the Users table and department name into the Work table so that the Roles, Login and Departments tables can be removed?  That way the corresponding Foreign Keys can also be removed.
> 2. As discussed before, we may not be working on the verification of hours.  In this case, what is the purpose of having leave_hours, contract_hour and available_hours?  Do we still need to keep track of these hours and build the function for updating leave hours (by extracting data from relevant spreadsheet) in the assign page?
> 3. Suggested Relationships:
> 
> image

> 1. Ideally we need to store and manage the login credential separately as we discussed before, so that it won't be mis-used.
> 2. This is only according to the spreadsheet provided by the client, so I guess we need to store the data in the database.
> 3. As workAllocation is designed by each transaction not per work, each work can be allocated to multiple users but each allocation will only direct to one and only one user. As for the sign, I'll change them accordingly to avoid confusion, Thanks!

**Comment by kylelhk** [comment]
> > 1. Other than Primary Key, there is only 1 field in the Roles, Login and Departments tables.  Can we add role name and password into the Users table and department name into the Work table so that the Roles, Login and Departments tables can be removed?  That way the corresponding Foreign Keys can also be removed.
> > 2. As discussed before, we may not be working on the verification of hours.  In this case, what is the purpose of having leave_hours, contract_hour and available_hours?  Do we still need to keep track of these hours and build the function for updating leave hours (by extracting data from relevant spreadsheet) in the assign page?
> > 3. Suggested Relationships:
> > 
> > image
> 
> > 1. Ideally we need to store and manage the login credential separately as we discussed before, so that it won't be mis-used.
> > 2. This is only according to the spreadsheet provided by the client, so I guess we need to store the data in the database.
> > 3. As workAllocation is designed by each transaction not per work, each work can be allocated to multiple users but each allocation will only direct to one and only one user. As for the sign, I'll change them accordingly to avoid confusion, Thanks!

Thanks for the clarification!

1. Agreed to keep the Roles, Login and Departments tables separately.  This is good for access control and data normalisation (e.g. the role of HoS can be retained in case of any deletion of HoS user).

2. Agreed to keep the hour fields - no harm to keep more data for better scalability, and these data can also be shown in the dashboard / view page / report.

3. Agreed to keep the one and only one relationship for WorkloadAllocations to Users.  Ordinality (zero or many) should be added to the (i) Users to WorkloadAllocations and (ii) Work to WorkloadAllocations relationships per our discussion earlier today.

**Review by kylelhk — APPROVED** [review]
Discussion has been conducted (see the comments added in the Conversation page).
Overall the schema looks good and no conflict is identified.

**Pull request merged**
